export const SET_USER_REGISTER_SUCCESS = 'SET_USER_REGISTER_SUCCESS'
export const SET_USER_REGISTER_FAIL = 'SET_USER_REGISTER_FAIL'


export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGIN_FAIL'